spring.application.name=Student_Management
server.port=8081

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/smgmt_db
spring.datasource.username=postgres
spring.datasource.password=Pashupati8

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true